# nginx-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server
spec:
  selector:
    app: nginx-server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: l7mp/net-debug:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://nginx-server);
            echo "{ \"statusCode\": $STATUS_CODE }";
            sleep 5;
          done
---
# virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-server
spec:
  hosts:
  - nginx-server
  http:
  - route:
      - destination:
          host: nginx-server
    fault:
      abort:
        percentage:
          value: 30  # 30% of requests will fail with 500
        httpStatus: 500