apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-cluster
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://opensearch-project.github.io/opensearch-k8s-operator
    targetRevision: 3.0.0
    chart: opensearch-cluster
    helm:
      releaseName: opensearch-cluster
      valueFiles:
      - $values-repo/releases/opensearch-cluster/values.yaml
  - repoURL: https://github.com/davidkornel/training.git
    targetRevision: HEAD
    ref: values-repo
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - ApplyOutOfSyncOnly=true #general
    - ServerSideApply=false