clusterFlows:
  - name: all-pods
    spec:
      globalOutputRefs:
        - logstash-tcp

clusterOutputs:
  - name: logstash-tcp
    spec:
      forward:
        servers:
          - host: logstash-logstash.logstash.svc
            port: 5514
        transport: tcp