clusterFlows:
  - name: all-pods
    spec:
      globalOutputRefs:
        - logstash-tcp

clusterOutputs:
  - name: logstash-tcp
    spec:
      forward:
        host: logstash-logstash.logstash.svc
        port: 5514