clusterFlows:
  - name: all-pods
    spec:
      globalOutputRefs:
        - logstash-tcp

clusterOutputs:
  - name: logstash-tcp
    spec:
      opensearch:
        host: opensearch-cluster.opensearch
        port: 9200
        user: admin
        password:
          valueFrom:
            secretKeyRef:
              name: logging-operator-opensearch-credential
              key: password
        scheme: https
        index_name: k8s-logs-03-10
        ssl_verify: false