clusterFlows:
  - name: all-pods
    spec:
      globalOutputRefs:
        - logstash-tcp

clusterOutputs:
  - name: logstash-tcp
    spec:
      opensearch:
        host: opensearch-cluster.opensearch
        port: 9200
        user: admin
        password:
          value: YWRtaW4=
        scheme: http
        index_name: kubernetes-logs
        ssl_verify: false