clusterFlows:
  - name: all-pods
    spec:
      globalOutputRefs:
        - logstash-syslog
clusterOutputs:
  - name: logstash-syslog
    spec:
      syslog:
        host: logstash-logstash.logstash.svc
        port: 5514
        protocol: tcp # I don't think that a valid field
        insecure: true