clusterFlows:
  - name: all-pods
    spec:
      match:
        - select:
            labels:
              app.kubernetes.io/name: logging-operator
      globalOutputRefs:
        - logstash-tcp

clusterOutputs:
  - name: logstash-tcp
    spec:
      opensearch:
        host: opensearch-cluster.opensearch
        port: 9200
        user: admin
        password:
          value: admin
        scheme: https
        index_name: kubernetes-logs
        ssl_verify: false