auth:
  rootUser: admin
  rootPassword: minioadmin
provisioning:
  enabled: true
  buckets:
    - name: opensearch-snapshots
      policy: none
      purge: false

persistence:
  enabled: true
  size: 2Gi

extraEnvVars:
- name: MINIO_DEBUG
  value: "true"
- name: BITNAMI_DEBUG
  value: "true"