image: "docker.io/davidkornel/logstash-opensearch"
imageTag: "v0.1.0"
resources:
  requests:
    cpu: "100m"
    memory: "600Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"
extraPorts:
  - containerPort: 514
    name: syslog
logstashPipeline:
  logstash.conf: |
    input {
      syslog {
        port => 514
        id => "my_first_syslog"
      }
      file {
        # Tail Kubernetes logs
        path => "/var/log/containers/*.log"
        start_position => "beginning"  # Start from the beginning of the file (for debugging/testing)
        sincedb_path => "/dev/null"    # Disable sincedb to prevent state tracking between restarts
      }
    }

    output {
      opensearch {
        hosts => ["https://opensearch-cluster.opensearch:9200"]
        index => "syslog-%{+YYYY.MM.dd}"
        user => "admin"
        password => "admin"
        ssl_certificate_verification => false
      }
    }