image: "docker.io/davidkornel/logstash-opensearch"
imageTag: "v0.1.0"
resources:
  requests:
    cpu: "100m"
    memory: "600Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"
extraPorts:
  - containerPort: 514
    name: syslog
service:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5514
      targetPort: 5514
      name: syslog

logstashPipeline:
  logstash.conf: |
    input {
      syslog {
        port => 5514
        id => "logging-operator-syslog"
      }
    }

    output {
      opensearch {
        hosts => ["https://opensearch-cluster.opensearch:9200"]
        index => "syslog-%{+YYYY.MM.dd}"
        user => "admin"
        password => "admin"
        ssl_certificate_verification => false
      }
    }