image: "docker.io/davidkornel/logstash-opensearch"
imageTag: "v0.1.0"
resources:
  requests:
    cpu: "100m"
    memory: "600Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"
extraPorts:
  - containerPort: 5514
    name: tcp-input
    protocol: TCP
service:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5514
      targetPort: 5514
      name: tcp-input

logstashPipeline:
  logstash.conf: |
    input {
      tcp {
        port => 5514
        codec => json_lines
        id => "logging-operator-tcp"
      }
    }

    filter {
      # Basic parsing and cleaning
      json {
        source => "message"
        skip_on_invalid_json => true
      }
      
      # Remove empty/null fields
      ruby {
        code => "
          event.to_hash.each do |k,v|
            if v.nil? || (v.is_a?(String) && v.empty?)
              event.remove(k)
            end
          end
        "
      }
    }

    output {
      stdout { codec => rubydebug }
      opensearch {
        hosts => ["https://opensearch-cluster.opensearch:9200"]
        index => "kubernetes-logs-%{+YYYY.MM.dd}"
        user => "admin"
        password => "admin"
        ssl_certificate_verification => false
        template_overwrite => true
      }
    }