cluster:
  general:
    serviceName: opensearch-cluster
    pluginsList:
      - repository-s3
    additionalConfig:
      plugins.repository.s3.allow_insecure_settings: "true"
  dashboards:
    enable: true
    resources:
      requests:
        memory: "500Mi"
        cpu: "200m"
      limits:
        memory: "800Mi"
        cpu: "500m"
  nodePools:
    - component: masters
      diskSize: "2Gi"
      replicas: 3
      resources:
        requests:
          memory: "600Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "800m"
      roles:
        - "cluster_manager"
        - "data"