cluster:
  general:
    serviceName: opensearch-cluster
    pluginsList:
      - repository-s3
    keystore:
    - secret:
        name: opensearch-credentials
      keyMappings:
        # Renames key accessKey in secret to s3.client.default.access_key in keystore
        accessKey: s3.client.default.access_key
        password: s3.client.default.secret_key
  snapshotRepositories:
  - name: opensearch-snapshots
    type: s3
    settings:
      bucket: opensearch-snapshots
      base_path: os-snapshot
      endpoint: https://minio.minio:9000
  dashboards:
    enable: true
    resources:
      requests:
        memory: "500Mi"
        cpu: "200m"
      limits:
        memory: "800Mi"
        cpu: "500m"
  nodePools:
    - component: masters
      diskSize: "2Gi"
      replicas: 3
      resources:
        requests:
          memory: "600Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "800m"
      roles:
        - cluster_manager
        - data