cluster:
  general:
    serviceName: opensearch-cluster
    pluginsList:
      - repository-s3
    version: 2.19.1
    snapshotRepositories:
      - name: "opensearch-snapshots"
        type: s3
        settings:
          bucket: opensearch-snapshots
          base_path: os-snapshot
          path_style_access: "true"
          endpoint: http://minio.minio:9000
          protocol: http
    keystore:
    - secret:
        name: opensearch-credentials
      keyMappings:
        # Renames key accessKey in secret to s3.client.default.access_key in keystore
        accessKey: s3.client.default.access_key
        password: s3.client.default.secret_key
    additionalVolumes:
      - path: "/usr/share/opensearch/config/ca.crt"
        subPath: "ca.crt"
        name: cacert
        secret:
          secretName: minio-crt
          items:
          - key: ca.crt
            path: "ca.crt"
            mode: 0400
    additionalConfig:
      plugins.security.ssl.http.truststore_filepath: "ca.crt"
      plugins.security.ssl.transport.truststore_filepath: "ca.crt"

  dashboards:
    enable: true
    version: 2.19.1
    resources:
      requests:
        memory: "500Mi"
        cpu: "200m"
      limits:
        memory: "800Mi"
        cpu: "500m"
  nodePools:
    - component: masters
      diskSize: "2Gi"
      replicas: 3
      resources:
        requests:
          memory: "600Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "800m"
      roles:
        - cluster_manager
        - data