logging:
  enabled: true

  clusterFlows:
    - name: all-pods
      spec:
        filterNamespaces:
          - default
          - opensearch
        filters:
          - record_transformer:
              enable_ruby: true
              records:
                - key: $.kubernetes.labels.app_
                  value: ${record.dig('kubernetes', 'labels', 'app')}
              remove_keys: $.kubernetes.labels.app
          - record_transformer:
              remove_keys: $.kubernetes.labels.istio
        globalOutputRefs:
          - opensearch-output

  clusterOutputs:
    - name: opensearch-output
      spec:
        opensearch:
          host: opensearch-cluster.opensearch
          port: 9200
          user: admin
          password:
            valueFrom:
              secretKeyRef:
                name: logging-operator-opensearch-credential
                key: password
          scheme: https
          index_name: k8s-logs-03-25
          ssl_verify: false
          ssl_version: TLSv1_2
          log_os_400_reason: false
          with_transporter_log: false
          buffer:
            timekey: 5s
            timekey_wait: 1s
            chunk_limit_size: 5MB
            total_limit_size: 1GB
            retry_max_times: 5
            retry_wait: 2s
            flush_thread_count: 4
            flush_mode: interval
            flush_interval: 1s
            overflow_action: block  # Prevents data loss by blocking new records
            retry_type: exponential_backoff
            retry_exponential_backoff_base: 2
            retry_max_interval: 30
            disable_retry_limit: false