grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: NodePort

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: false
  service:
    type: NodePort
