prometheus:
  enabled: true
  prometheusSpec:
    scrapeInterval: 15s
    enableRemoteWriteReceiver: true
    remoteWrite:
    - url: http://mimir-distributed-nginx.mimir:80/api/v1/push
  additionalServiceMonitors:
    - name: example-app
      additionalLabels:
        app: example-app
      namespaceSelector:
        matchNames:
          - example-app
      selector:
        matchLabels:
          app: example-app
      endpoints:
        - port: web
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: standard-rwo
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 5Gi



grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: NodePort
  # persistence:
  #   enabled: true
  #   type: sts
  #   storageClassName: standard-rwo
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 3Gi
  #   finalizers:
  #     - kubernetes.io/pvc-protection
  additionalDataSources:
    - name: mimir
      type: prometheus
      url: http://mimir-distributed-nginx.mimir:80/prometheus
      version: 1


alertmanager:
  enabled: false
  service:
    type: NodePort
