prometheus:
  enabled: true
  prometheusSpec:
    enableRemoteWriteReceiver: true
    remoteWrite:
    - url: http://mimir-nginx.monitoring.svc.cluster.local:80/api/v1/push
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: standard-rwo
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 5Gi

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: NodePort
  persistence:
    enabled: true
    type: sts
    storageClassName: standard-rwo
    accessModes:
      - ReadWriteOnce
    size: 3Gi
    finalizers:
      - kubernetes.io/pvc-protection


alertmanager:
  enabled: false
  service:
    type: NodePort
